language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
# command to install package
install:
  - pip install py-notify
  - apt-get install python-notify
  - python setup.py install
# command to run tests
script:
  - nosetests
#after_success:
#  coveralls
notifications:
  email: false
