language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
# command to install package
install:
  - pip install ImageScraper
  - python setup.py install
# command to run tests
script:
  - image-scraper ananth.co.in
#after_success:
#  coveralls
notifications:
  email: false
